---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: example.show

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions:
  - allOf:
      - property:
          name: Monthlysubscription
          operator: is-true
      - property:
          name: rox.app.release
          operator: in-array
          operands:
            - hello
      - property:
          name: Test prop fmdemo
          operator: is-undefined
    flagValue: false
